### ISSUE TITLE
No config file detected error

### ISSUE THREAD

**Issue by vijayjb** [ezekg/git-hound#10]
I am finding it difficult to follow the help doc.  I have the config file in "/go/bin/.githound.yml" .When i run "git-hound sniff" getting the error "No config file detected" .

What is the right step to set it up.  Thanks!!

**Comment by ezekg** [comment]
By default, the script looks for a config file within the current directory. If you want to use a global config, you will need to specify the absolute path like so:

```
git hound -config=/go/bin/.githound.yml sniff
```

**Comment by vijayjb** [comment]
Thanks for the reply.  Having in local directory works. 
But referring the global config doesn't work.

$ git hound -config=~/go/bin/.githound.yml 
No config file detected
$ ls ~/go/bin/.githound.yml 
/~/go/bin/.githound.yml
Also, can this be run on repo url?

**Comment by vijayjb** [comment]
Is there a issue with passing config files as input parameters? Appreciate any help.

$ git hound -config=~/go/bin/.githound.yml
No config file detected
$ ls /go/bin/.githound.yml
//go/bin/.githound.yml

**Comment by ezekg** [comment]
It needs to be an absolute path. The `~` is not currently expanded.

**Comment by vijayjb** [comment]
Thanks for the answer, it worked!!
Is there any option to run this with "remote git repo URL" option?

**Comment by ezekg** [comment]
Not currently. I'd be open to a PR that allows you to pipe in a config file's contents (so you could pipe in a `curl` request's body), but I don't have time to build it out myself. Not interested in adding functionality to download a file via a URL and use that config, though. For now, I'd download the file to a local config file. or clone the repo and use the absolute path to the repo.

**Comment by vijayjb** [comment]
If we can run only on the cloned local repo, doesn't it catch the vulnerabilities in other branches? 
Thanks for your help!!
