### ISSUE TITLE
Parsing of time in git seems like its broken and blocking work

### ISSUE THREAD

**Issue by memoag** [ezekg/git-hound#7]
parsing time "" as "2006-01-02 15:04:05.000000000 -0700": cannot parse "" as "2006"

**Comment by ezekg** [comment]
I need more details on the issue, as I’m not entirely sure what to make of your post. Can you show me reproducible steps and what the proble is vs expected result?

**Comment by memoag** [comment]
Well, to start with I am not sure what the expect result is.  However, I added regex to flag everything with a warning, creating a yam file at the root of the repo in question.

#Output warning on match but continue
warn:
  - '(?i)user(name)?\W*[:=,]\W*.+$'
  - '\/Users\/\w+\/'
  - '(?i)initiali\w*.+$'
  - '.*'
# Fail immediately upon match
fail:
  - '[''"](?!.*[\s])(?=.*[A-Za-z])(?=.*[0-9])(?=.*[!@#$&*])?.{16,}[''"]'
  - '(?i)db_(user(name)?|pass(word)?|name)\W*[:=,]\W*.+$'
  - '(?i)pass(word)?\W*[:=,]\W*.+$'
  - '(?i)secret\W*.+$'
  - '(?i)token\W*.+$'
# Skip on matched filename
skip:
  - '\.example$'
  - '\.sample$'


Even when I use sample yaml I get the same response:

[some dudes Mac prompt]$ git hound sniff
parsing time "" as "2006-01-02 15:04:05.000000000 -0700": cannot parse "" as "2006"

When I try 
git hound sniff HEAD

I get no result at all

**Comment by ezekg** [comment]
Works fine for me. What version of Git do you have and what OS? [This Go issue](https://github.com/golang/go/issues/4493) seems related, but I'm not using the `time` package, so this may be an issue on your end or with a dependency.

**Comment by memoag** [comment]
git version 2.14.3 (Apple Git-98)
 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
(macOS Sierra 10.12.16)

**Comment by ezekg** [comment]
Okay, looks like an issue in https://github.com/sourcegraph/go-diff/pull/17. Needed to update to latest version of sourcegraph/go-diff. Could you try the new release, v0.6.2?
